### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by asg358** [mohanbe/pyR305#1]
Put Finger:
I am getting the following error when I ran the code for enroll in raspberry pi3. I have interfaced r305 with rpi3 using cp2102 adapter.
Please help
Traceback (most recent call last):
  File "/home/pi/Downloads/pyR305-master/R305/demonew.py", line 6, in <module>
    f.enroll()
  File "/home/pi/Downloads/pyR305-master/R305/Finger.py", line 11, in enroll
    self.f.getimg()
  File "/home/pi/Downloads/pyR305-master/R305/FingerPrint.py", line 43, in getimg
    x=list(d)[4]
TypeError: 'NoneType' object is not iterable

**Comment by adamob99** [comment]
I am having this same problem, any solution?

**Comment by mohanbe** [comment]
Hey Sorry, As I'm stopped developing it. I'll look in to this and upload the new build.

I have done many changes but haven't uploaded and will be uploading it soon.
